# Generated by Django 2.2.4 on 2019-09-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applications',
        ),
    ]
