# Generated by Django 2.2.4 on 2019-09-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='documents/')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs', models.IntegerField(choices=[(0, 'Walk-ins'), (1, 'BPO'), (2, 'Teaching'), (3, 'Diploma_jobs'), (4, 'Tech_support'), (5, 'Finance'), (6, 'Part_time'), (7, 'Health_care'), (8, 'Hospitality'), (9, 'Internships'), (10, 'Research'), (11, 'Security')], default=5)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('location', models.CharField(default='Nairobi', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_on'],
            },
        ),
    ]
