# Generated by Django 2.2.4 on 2019-09-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='email',
            new_name='from_email',
        ),
    ]
