# Generated by Django 2.2.4 on 2019-08-23 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Jobs'},
        ),
    ]
